# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-03-02 09:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0004_environment_daily_environment_monthly_environment_weekly'),
    ]

    operations = [
        migrations.AddField(
            model_name='environment_daily',
            name='humidity_high',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='environment_daily',
            name='humidity_low',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='environment_daily',
            name='light_high',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='environment_daily',
            name='light_low',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='environment_daily',
            name='temperature_high',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='environment_daily',
            name='temperature_low',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
    ]
