# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-03-22 08:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0005_auto_20160302_1720'),
    ]

    operations = [
        migrations.CreateModel(
            name='Suyuan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field1', models.CharField(max_length=128)),
                ('field2', models.FloatField()),
                ('field3', models.CharField(max_length=128)),
                ('field4', models.DateField()),
            ],
        ),
    ]
