# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-05-03 07:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0007_auto_20160429_1638'),
    ]

    operations = [
        migrations.CreateModel(
            name='humidity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sensor_id', models.CharField(max_length=128)),
                ('humidity', models.FloatField(blank=True, default=None, null=True)),
                ('record_date', models.DateTimeField(default=None)),
            ],
        ),
        migrations.CreateModel(
            name='lux',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sensor_id', models.CharField(max_length=128)),
                ('lux', models.FloatField(blank=True, default=None, null=True)),
                ('record_date', models.DateTimeField(default=None)),
            ],
        ),
        migrations.CreateModel(
            name='temperature',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sensor_id', models.CharField(max_length=128)),
                ('temperature', models.FloatField(blank=True, default=None, null=True)),
                ('record_date', models.DateTimeField(default=None)),
            ],
        ),
    ]
