# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-05-03 09:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0009_auto_20160503_1520'),
    ]

    operations = [
        migrations.CreateModel(
            name='Environment_Daily_new',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sensor_id', models.CharField(max_length=128)),
                ('temperature', models.FloatField(blank=True, default=None, null=True)),
                ('temperature_low', models.FloatField(blank=True, default=None, null=True)),
                ('temperature_high', models.FloatField(blank=True, default=None, null=True)),
                ('humidity', models.FloatField(blank=True, default=None, null=True)),
                ('humidity_low', models.FloatField(blank=True, default=None, null=True)),
                ('humidity_high', models.FloatField(blank=True, default=None, null=True)),
                ('light', models.FloatField(blank=True, default=None, null=True)),
                ('light_low', models.FloatField(blank=True, default=None, null=True)),
                ('light_high', models.FloatField(blank=True, default=None, null=True)),
                ('record_date', models.DateTimeField(default=None)),
            ],
        ),
    ]
